# Generated by Django 5.0.14 on 2026-04-24 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('input_payload', models.JSONField()),
                ('plan_payload', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
